<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 C:\Users\hophe\OneDrive\Bureau\personal\spooky3D\static\models\ghost.glb --transform
-->

<script>
  import * as Threlte from '@threlte/core';
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'
	import { DirectionalLight, Material, MeshBasicMaterial, MeshDepthMaterial, MeshStandardMaterial, PointLight } from 'three';
  import { browser } from '$app/environment';
  import { Pane } from 'tweakpane';
  export const ref = new Group()
  export let color = "red"; // Définir la couleur par défaut
  export const ghostLight1 = {
      position: {
        x: 1.18,
        y: 1.90,
        z: 0.99
      }
    };
    export const ghostLight2 = {
      position: {
        x: -0.12,
        y: 1.90,
        z: -0.99
      }
    };
    export const ghost = {
      position: {
        x: 0,
        y: 2.6,
        z: -0.3
      }
    }
  const gltf = useGltf('/models/ghost-transformed.glb', { useDraco: true })

  

  if (browser) {
		const pane = new Pane({
			title: 'Scene'
		});
		const ghost = pane.addFolder({
			title: 'Ghost'
		});
    // FIRST GHOST LIGHT
		let ghostLight1Controls = pane.addFolder({
			title: 'ghostLight1'
		});
		ghostLight1Controls.addBinding(ghostLight1, 'position', {
			multiline: true,
			bufferSize: 3
		});
		ghostLight1Controls.on('change', (ev) => {
				ghostLight1.position = ev.value;
		});
    // SECOND GHOST LIGHT
    let ghostLight2Controls = pane.addFolder({
      title: 'ghostLight2'
    });
    ghostLight2Controls.addBinding(ghostLight2, 'position', {
      multiline: true,
      bufferSize: 3
    });
    ghostLight2Controls.on('change', (ev) => {
        ghostLight2.position = ev.value;
    });


	}
  const component = forwardEventHandlers()

  let levitationAmplitude = 0.2; // Ajuste cette valeur selon la hauteur de lévitation souhaitée
  let levitationDirection = 1; // 1 pour monter, -1 pour descendre

  Threlte.useTask((delta) => {
    levitationAmplitude += delta * 0.2 * levitationDirection;
    console.log(levitationAmplitude);

    // Changer la direction lorsque la hauteur maximale ou minimale est atteinte
    if (levitationAmplitude >= 0.4 || levitationAmplitude <= 0.2) {
      levitationDirection *= -1;
    }
  });


</script>

{#if browser}
<T is={ref} dispose={false} {...$$restProps} bind:this={$component} position={[ghost.position.x,ghost.position.y + levitationAmplitude,ghost.position.z ]}>
 
  {#await gltf} 
    <slot name="fallback" />
  {:then gltf}
  <T.PointLight
      position={[ghostLight1.position.x, ghostLight1.position.y, ghostLight1.position.z]}
      color={'#fc86f3'}
      intensity={5}
    />
    <T.PointLight
      position={[ghostLight2.position.x,ghostLight2.position.y, ghostLight2.position.z]}
      color={'#fc86f3'}
      intensity={5}
    />
    <T.Mesh geometry={gltf.nodes.Ghost002.geometry} material={gltf.materials.Outline} material.color={color}  scale={0.53} rotation.y={45} >
      
    </T.Mesh>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
{/if}